sudo: false
language: node_js
node_js:
- '0.12'
before_install:
- mkdir -p .git
- git config --global credential.helper "store --file=$HOME/.git/credentials"
- git config --global user.email "carlos@adaptive.me"
- git config --global user.name "carloslozano"
- git config --global push.default simple
- echo "https://${GH_TOKEN}:@github.com" > $HOME/.git/credentials
- git remote set-url origin https://github.com/AdaptiveMe/npm-adaptiveme-nibble.git
script:
- npm test
deploy:
  provider: npm
  email: carlos@adaptive.me
  api_key:
    secure: U17BuKMupgH4TqiGbeON8mNoGL+6k5YL7ETViTuJb17YT2NhtcgBGlGg2UfBsOLrDR/MJESG7BEnRLygD/3r/pBdgN6Dvb9E0vpA2Rv5LrVI6x4pQw2/Kw3un4yVDfzdTCcdIQQpwSJcezt0k5gb0EijNTQzpt0daV5QDTMyasU=
  on:
    tags: true
    repo: AdaptiveMe/npm-adaptiveme-nibble
env:
  global:
    secure: Ut+Y2cGFjhAGojcs4vvshrZq+8xz2VscDmzkE/Ri8ic2Hr3crawYIkWp3aSQoywklD4Rm/zvjenRBXbPIBOmuvZv1SW+5VZMoWBXkvrkgWh0wM6lEfGAI0i1Df9t5afIZPC4ZclkSbF4iGyxwsjKYYHNg5z/7/WhxzCR2UPp6to=
